2024-07-03 10:17:24,689 - mmseg - INFO - Loaded 1449 images
Traceback (most recent call last):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/zegenv/lib/python3.9/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/segmentor/inner_zegclip.py", line 54, in __init__
    super(ZegCLIP, self).__init__(**args)
NameError: name 'ZegCLIP' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/test.py", line 330, in <module>
    main()
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/test.py", line 225, in main
    model = build_segmentor(cfg.model, test_cfg=cfg.get("test_cfg"))
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/mmseg/models/builder.py", line 48, in build_segmentor
    return SEGMENTORS.build(
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/zegenv/lib/python3.9/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/zegenv/lib/python3.9/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/zegenv/lib/python3.9/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
NameError: InnerZegCLIP: name 'ZegCLIP' is not defined
