/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
[i 0801 11:48:59.650770 28 compiler.py:956] Jittor(1.3.8.5) src: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor
[i 0801 11:48:59.654734 28 compiler.py:957] g++ at /usr/bin/g++(7.5.0)
[i 0801 11:48:59.654802 28 compiler.py:958] cache_path: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4xb0/AMDEPYC753232-x73/default
[i 0801 11:48:59.659587 28 __init__.py:411] Found nvcc(11.0.221) at /usr/local/cuda/bin/nvcc.
[i 0801 11:48:59.664333 28 __init__.py:411] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0801 11:48:59.792440 28 compiler.py:1011] cuda key:cu11.0.221_sm_86
[i 0801 11:49:00.344066 28 __init__.py:227] Total mem: 503.74GB, using 16 procs for compiling.
[i 0801 11:49:06.137492 28 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0801 11:49:06.315958 28 init.cc:62] Found cuda archs: [86,]
[w 0801 11:49:06.392683 28 compiler.py:1384] CUDA arch(86)>80 will be backward-compatible
[i 0801 11:49:07.651070 28 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0801 11:49:08.039983 84 compiler.py:956] Jittor(1.3.8.5) src: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor
[i 0801 11:49:08.045078 84 compiler.py:957] g++ at /usr/bin/g++(7.5.0)
[i 0801 11:49:08.045152 84 compiler.py:958] cache_path: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4xb0/AMDEPYC753232-x73/default
[i 0801 11:49:08.050203 84 __init__.py:411] Found nvcc(11.0.221) at /usr/local/cuda/bin/nvcc.
[i 0801 11:49:08.054629 84 __init__.py:411] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0801 11:49:08.190852 84 compiler.py:1011] cuda key:cu11.0.221_sm_86
[i 0801 11:49:08.670947 84 __init__.py:227] Total mem: 503.74GB, using 16 procs for compiling.
[i 0801 11:49:08.845241 84 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0801 11:49:08.983814 84 init.cc:62] Found cuda archs: [86,]
[w 0801 11:49:09.058647 84 compiler.py:1384] CUDA arch(86)>80 will be backward-compatible
[i 0801 11:49:10.376416 84 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0801 11:49:10.522519 36 compiler.py:956] Jittor(1.3.8.5) src: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor
[i 0801 11:49:10.526918 36 compiler.py:957] g++ at /usr/bin/g++(7.5.0)
[i 0801 11:49:10.526987 36 compiler.py:958] cache_path: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4xb0/AMDEPYC753232-x73/default
[i 0801 11:49:10.531814 36 __init__.py:411] Found nvcc(11.0.221) at /usr/local/cuda/bin/nvcc.
[i 0801 11:49:10.536061 36 __init__.py:411] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0801 11:49:10.671594 36 compiler.py:1011] cuda key:cu11.0.221_sm_86
[i 0801 11:49:11.141618 36 __init__.py:227] Total mem: 503.74GB, using 16 procs for compiling.
[i 0801 11:49:11.318504 36 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0801 11:49:11.449789 36 init.cc:62] Found cuda archs: [86,]
[w 0801 11:49:11.524033 36 compiler.py:1384] CUDA arch(86)>80 will be backward-compatible
[i 0801 11:49:12.807248 36 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0801 11:49:12.966855 36 compiler.py:956] Jittor(1.3.8.5) src: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor
[i 0801 11:49:12.971753 36 compiler.py:957] g++ at /usr/bin/g++(7.5.0)
[i 0801 11:49:12.971826 36 compiler.py:958] cache_path: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4xb0/AMDEPYC753232-x73/default
[i 0801 11:49:12.977212 36 __init__.py:411] Found nvcc(11.0.221) at /usr/local/cuda/bin/nvcc.
[i 0801 11:49:12.982437 36 __init__.py:411] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0801 11:49:13.120775 36 compiler.py:1011] cuda key:cu11.0.221_sm_86
[i 0801 11:49:13.603644 36 __init__.py:227] Total mem: 503.74GB, using 16 procs for compiling.
[i 0801 11:49:13.780940 36 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0801 11:49:13.892657 36 init.cc:62] Found cuda archs: [86,]
[w 0801 11:49:13.967255 36 compiler.py:1384] CUDA arch(86)>80 will be backward-compatible
[i 0801 11:49:15.210961 36 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0801 11:49:25.038063 84 cuda_flags.cc:49] CUDA enabled.
[i 0801 11:49:26.148462 36 cuda_flags.cc:49] CUDA enabled.
[i 0801 11:49:26.166199 36 cuda_flags.cc:49] CUDA enabled.
[i 0801 11:49:26.270422 28 cuda_flags.cc:49] CUDA enabled.

Compiling Operators(8/16) used: 3.49s eta: 3.49s Compiling Operators(15/16) used: 4.49s eta: 0.299s Compiling Operators(16/16) used: 5.49s eta:    0s 

Compiling Operators(3/4) used: 3.43s eta: 1.14s Compiling Operators(4/4) used: 4.43s eta:    0s 

Compiling Operators(1/2) used: 3.37s eta: 3.37s Compiling Operators(2/2) used: 4.37s eta:    0s 
/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/losses/cross_entropy_loss.py:55: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with Jittor official cross_entropy, set ``avg_non_ignore=True``.
  warnings.warn(
/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/losses/cross_entropy_loss.py:55: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with Jittor official cross_entropy, set ``avg_non_ignore=True``.
  warnings.warn(
/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/losses/cross_entropy_loss.py:55: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with Jittor official cross_entropy, set ``avg_non_ignore=True``.
  warnings.warn(
/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/losses/cross_entropy_loss.py:55: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with Jittor official cross_entropy, set ``avg_non_ignore=True``.
  warnings.warn(

Compiling Operators(1/6) used: 3.42s eta: 17.1s Compiling Operators(6/6) used: 4.42s eta:    0s 

Compiling Operators(4/5) used: 3.43s eta: 0.857s Compiling Operators(5/5) used: 4.43s eta:    0s 

Compiling Operators(3/3) used: 4.38s eta:    0s 

Compiling Operators(3/3) used: 4.37s eta:    0s 

Compiling Operators(1/4) used: 3.42s eta: 10.3s Compiling Operators(4/4) used: 4.42s eta:    0s 
[e 0801 11:50:06.378770 36 log.cc:258] Caught SIGINT, quick exit
[e 0801 11:50:06.378752 84 log.cc:258] Caught SIGINT, quick exit
[e 0801 11:50:06.547431 28 log.cc:258] Caught SIGINT, quick exit
[e 0801 11:50:06.565028 36 log.cc:258] Caught SIGINT, quick exit
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 26) of binary: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/bin/python
Traceback (most recent call last):
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/run_net.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-08-01_11:50:09
  host      : ae01116-178661.0-aisurrey19.surrey.ac.uk
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 27)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-08-01_11:50:09
  host      : ae01116-178661.0-aisurrey19.surrey.ac.uk
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 28)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-08-01_11:50:09
  host      : ae01116-178661.0-aisurrey19.surrey.ac.uk
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 29)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-08-01_11:50:09
  host      : ae01116-178661.0-aisurrey19.surrey.ac.uk
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 26)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
